import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import {initAuth,authHeaders} from './auth';

const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
type Msg={role:'user'|'assistant';content:string;citations?:any[]};

function App(){
 const [messages,setMessages]=useState<Msg[]>([]); const [input,setInput]=useState(''); const [cid,setCid]=useState<string>(); const [busy,setBusy]=useState(false); const [recording,setRecording]=useState(false); const [docs,setDocs]=useState<any[]>([]); const [user,setUser]=useState<any>(); const media=useRef<MediaRecorder|null>(null); const chunks=useRef<Blob[]>([]);
 useEffect(()=>{initAuth().then(()=>fetch(API+'/api/v1/me',{headers:authHeaders()})).then(r=>r.json()).then(setUser).catch(()=>{}); fetch(API+'/api/v1/documents',{headers:authHeaders()}).then(r=>r.json()).then(setDocs).catch(()=>{});},[]);
 async function send(text=input, speak=false){ if(!text.trim()||busy)return; setInput(''); setMessages(m=>[...m,{role:'user',content:text}]); setBusy(true); try{const r=await fetch(API+'/api/v1/chat',{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({message:text,conversation_id:cid,use_knowledge:true})}); const d=await r.json(); if(!r.ok)throw new Error(d.detail||'Request failed'); setCid(d.conversation_id); setMessages(m=>[...m,{role:'assistant',content:d.answer,citations:d.citations}]); if(speak){ try{const ar=await fetch(API+'/api/v1/voice/synthesize',{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({text:d.answer})}); if(ar.ok){const audio=new Audio(URL.createObjectURL(await ar.blob())); await audio.play();}}catch(_e){} }}catch(e:any){setMessages(m=>[...m,{role:'assistant',content:'Erreur: '+e.message}]);}finally{setBusy(false)}}
 async function startRec(){ const stream=await navigator.mediaDevices.getUserMedia({audio:true}); const rec=new MediaRecorder(stream); media.current=rec; chunks.current=[]; rec.ondataavailable=e=>chunks.current.push(e.data); rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop()); const blob=new Blob(chunks.current,{type:'audio/webm'}); const fd=new FormData(); fd.append('file',blob,'voice.webm'); setBusy(true); try{const r=await fetch(API+'/api/v1/voice/transcribe',{method:'POST',headers:authHeaders(),body:fd}); const d=await r.json(); if(d.text){setBusy(false); await send(d.text,true);}}finally{setBusy(false)}}; rec.start(); setRecording(true); }
 function stopRec(){media.current?.stop(); setRecording(false)}
 async function upload(e:any){const file=e.target.files?.[0];if(!file)return;const fd=new FormData();fd.append('file',file);const r=await fetch(API+'/api/v1/documents',{method:'POST',headers:authHeaders(),body:fd});const d=await r.json();if(r.ok)setDocs(x=>[d,...x]);else alert(d.detail||'Upload failed')}
 return <div className="app"><aside><div className="brand">Enterprise AI</div><div className="user">{user?.name||'Employee'}<small>{user?.department||'Internal Assistant'}</small></div><label className="upload">+ Add knowledge<input type="file" hidden accept=".pdf,.docx,.txt,.md,.csv,.json" onChange={upload}/></label><h4>Knowledge</h4>{docs.slice(0,10).map(d=><div className="doc" key={d.id}>📄 {d.filename}</div>)}</aside><main><header><div><b>Employee Assistant</b><span>Sovereign · Local AI</span></div><div className="status">● Online</div></header><section className="chat">{messages.length===0&&<div className="welcome"><h1>Bonjour{user?.name?', '+user.name:''} 👋</h1><p>Posez une question sur les procédures, documents ou services de l'entreprise.</p><div className="suggestions"><button onClick={()=>send('Quelles sont les principales procédures disponibles ?')}>Explorer les procédures</button><button onClick={()=>send('Comment fonctionne cet assistant ?')}>Comment fonctionne l’IA ?</button></div></div>}{messages.map((m,i)=><div className={'msg '+m.role} key={i}><div className="bubble">{m.content}{m.citations?.length>0&&<div className="sources"><b>Sources</b>{m.citations.map((c:any,j:number)=><div key={j}>📄 {c.filename}</div>)}</div>}</div></div>)}{busy&&<div className="msg assistant"><div className="bubble typing">● ● ●</div></div>}</section><div className="composer"><button className={'mic '+(recording?'recording':'')} onClick={recording?stopRec:startRec}>🎤</button><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={recording?'Écoute en cours…':'Écrivez votre message…'} disabled={recording}/><button className="send" onClick={()=>send()}>➤</button></div></main></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
